-- Generated by spritter v1.2.0 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = {1, 2, 0},
  ["file_count"] = 1,
  ["height"] = 189,
  ["line_length"] = 7,
  ["lines_per_file"] = 3,
  ["scale"] = 0.5,
  ["shift"] = {x = 1.5 / 64, y = 10.5 / 64},
  ["sprite_count"] = 21,
  ["width"] = 69,
}
