-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 83,
  ["line_length"] = 17,
  ["lines_per_file"] = 19,
  ["name"] = "1",
  ["scale"] = 1,
  ["shift"] = {x = 0 / 32, y = 0 / 32},
  ["sprite_count"] = 320,
  ["width"] = 97,
}
