-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 75,
  ["line_length"] = 16,
  ["lines_per_file"] = 20,
  ["name"] = "10",
  ["scale"] = 1,
  ["shift"] = {x = -0.5 / 32, y = 0 / 32},
  ["sprite_count"] = 320,
  ["width"] = 96,
}
