-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 63,
  ["line_length"] = 4,
  ["lines_per_file"] = 5,
  ["name"] = "12",
  ["scale"] = 1,
  ["shift"] = {x = 0 / 32, y = 2.5 / 32},
  ["sprite_count"] = 20,
  ["width"] = 76,
}
