-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 92,
  ["line_length"] = 18,
  ["lines_per_file"] = 18,
  ["name"] = "15",
  ["scale"] = 1,
  ["shift"] = {x = 0 / 32, y = -7.5 / 32},
  ["sprite_count"] = 320,
  ["width"] = 97,
}
