_G.maraxsis = require "scripts.constants"
require "lib.lib"

require "scripts.map-gen.maraxsis"
require "scripts.map-gen.maraxsis-trench"
require "scripts.map-gen.map-gen-migration"
require "scripts.submarine"
require "scripts.drowning"
require "scripts.nightvision"
require "scripts.pressure-dome"
require "scripts.composite-entity"
require "scripts.sand-extractor"
require "scripts.hydro-plant"
require "scripts.project-seadragon"
require "scripts.swimming"
require "scripts.salt-reactor"
require "scripts.trench-duct"
require "scripts.abyssal-diving-gear"
require "scripts.remote"
require "scripts.fishing-tower"

maraxsis.finalize_events()
