require 'lib.lib'

require 'prototypes.submarine'
require 'prototypes.technology'
require 'prototypes.glass'
require 'prototypes.quarkals'
require 'prototypes.wyrm'
require 'prototypes.water-treatment'
require 'prototypes.big-cliff-explosive'
require 'prototypes.hydraulic-science-pack'
require 'prototypes.autoplace'
require 'prototypes.tile.lava'
require 'prototypes.tile.water'