-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 323,
  ["line_length"] = 8,
  ["lines_per_file"] = 16,
  ["scale"] = 0.5,
  ["shift"] = {0, 0},
  ["sprite_count"] = 128,
  ["width"] = 600,
}
