-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["filename"] = "__maraxsis__/graphics/entity/sonar/lights/hr-light-1-on.png",
  ["file_count"] = 1,
  ["height"] = 71,
  ["line_length"] = 1,
  ["lines_per_file"] = 1,
  ["name"] = "c",
  ["scale"] = 1,
  ["shift"] = {x = -118 / 32, y = 144.5 / 32},
  ["sprite_count"] = 1,
  ["width"] = 84,
}
