-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ['filename'] = '__maraxsis__/graphics/entity/sonar/lights/hr-light-1.png',
  ['file_count'] = 1,
  ['height'] = 96,
  ['line_length'] = 1,
  ['lines_per_file'] = 1,
  ['name'] = 'a',
  ['scale'] = 1,
  ['shift'] = {x = -117 / 32, y = 106 / 32},
  ['sprite_count'] = 1,
  ['width'] = 66,
}
