-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["filename"] = "__maraxsis__/graphics/entity/sonar/lights/hr-light-2.png",
  ["file_count"] = 1,
  ["height"] = 49,
  ["line_length"] = 1,
  ["lines_per_file"] = 1,
  ["name"] = "b",
  ["scale"] = 1,
  ["shift"] = {x = 121.5 / 32, y = -25.5 / 32},
  ["sprite_count"] = 1,
  ["width"] = 45,
}
