-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["filename"] = "__maraxsis__/graphics/entity/sonar/lights/hr-light-2-on.png",
  ["file_count"] = 1,
  ["height"] = 72,
  ["line_length"] = 1,
  ["lines_per_file"] = 1,
  ["name"] = "d",
  ["scale"] = 1,
  ["shift"] = {x = 127 / 32, y = -29 / 32},
  ["sprite_count"] = 1,
  ["width"] = 66,
}
