-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ['hr-light-1'] = require('hr-light-1'),
  ['hr-light-2'] = require('hr-light-2'),
  ['hr-light-1-on'] = require('hr-light-1-on'),
  ['hr-light-2-on'] = require('hr-light-2-on'),
}
