-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 419,
  ["line_length"] = 8,
  ["lines_per_file"] = 16,
  ["scale"] = 0.5,
  ["shift"] = {10 + 0 / 64, 10 + 39.5 / 64},
  ["sprite_count"] = 128,
  ["width"] = 738,
}
