-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 234,
  ["line_length"] = 8,
  ["lines_per_file"] = 8,
  ["name"] = "body",
  ["scale"] = 1,
  ["shift"] = {x = 6 / 32, y = 11 / 32},
  ["sprite_count"] = 64,
  ["width"] = 244,
}
