-- Generated by spritter v0.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 256,
  ["line_length"] = 8,
  ["lines_per_file"] = 32,
  ["name"] = "body",
  ["scale"] = 1,
  ["shift"] = {x = 0 / 32, y = 0 / 32},
  ["sprite_count"] = 64,
  ["width"] = 256,
}
