-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 101,
  ["line_length"] = 6,
  ["lines_per_file"] = 11,
  ["name"] = "light",
  ["scale"] = 1,
  ["shift"] = {x = 0 / 32, y = 45.5 / 32},
  ["sprite_count"] = 66,
  ["width"] = 248,
}
