-- Generated by spritter v0.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 225,
  ["line_length"] = 11,
  ["lines_per_file"] = 36,
  ["name"] = "mask",
  ["scale"] = 1,
  ["shift"] = {x = 8 / 32, y = 15.5 / 32},
  ["sprite_count"] = 128,
  ["width"] = 240,
}
