-- Generated by spritter v0.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["body"] = require("body"),
  ["full-body"] = require("full-body"),
  ["light"] = require("light"),
  ["mask"] = require("mask"),
  ["shadow"] = require("shadow"),
}
