-- Generated by spritter v0.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["file_count"] = 1,
  ["height"] = 212,
  ["line_length"] = 11,
  ["lines_per_file"] = 38,
  ["name"] = "submerged",
  ["scale"] = 1,
  ["shift"] = {x = 0 / 32, y = 0 / 32},
  ["sprite_count"] = 128,
  ["width"] = 250,
}
