-- Generated by spritter v0.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["body"] = require("body"),
  ["light"] = require("light"),
  ["mask"] = require("mask"),
  ["shadow"] = require("shadow"),
  ["submerged"] = require("submerged"),
}
